apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: ns-talk
spec:
  type: ClusterIP
  selector:
    component: web
    resource: api
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: ns-talk
spec:
  type: NodePort
  selector:
    component: web
    resource: api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30100
